import {DURATION,clamp,defaults,sanitize,readSettings,pictureRect,timeAtScroll,scrollAtTime,clock,chapters} from './view-state.mjs';
import {copy} from './copy.mjs';
const $ = s => document.querySelector(s);
const params=new URLSearchParams(location.search),lang=params.get('lang')==='ar'?'ar':'en',ar=lang==='ar',text=copy[lang];
document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';
if(ar){document.title='MK Business OS — من الإشارة إلى الاستراتيجية';document.querySelector('h1').textContent=document.title;$('#runway').setAttribute('aria-label','مرّر لاستكشاف MK Business OS');$('#stage').setAttribute('aria-label','فيلم Business OS بالتمرير');$('#picture').setAttribute('aria-label','فيلم ميزات MK Business OS يتحرك بتمريرك');$('#watch-dialog').setAttribute('aria-label','شاهد MK Business OS مع الموسيقى الأصلية');$('#watch-video').setAttribute('aria-label','MK Business OS مع الموسيقى الأصلية');$('.more').setAttribute('aria-label','المزيد من أفلام الأعمال');$('.film-meta').textContent='01:48 · ٨ عوالم';$('#crop-settings legend').textContent='القص';$('#share-link').setAttribute('aria-label','رابط إعدادات العرض');}
document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=text[el.dataset.copy]);
document.querySelectorAll('[data-label]').forEach(el=>el.setAttribute('aria-label',text[el.dataset.label]));
document.querySelectorAll('[data-home]').forEach(el=>el.href=`../${lang}/#work`);
document.querySelectorAll('[data-work]').forEach(el=>el.href=`../${lang}/work/${el.dataset.work}/`);
$('#language').href=`?lang=${ar?'en':'ar'}`;$('#language').lang=ar?'en':'ar';$('#language').textContent=ar?'English':'العربية';
const stage=$('#stage'),runway=$('#runway'),video=$('#decoder'),picture=$('#picture'),ambient=$('#ambient'),ctx=picture.getContext('2d'),bg=ambient.getContext('2d'),timeline=$('#timeline'),loading=$('#loading'),form=$('#view-form'),watch=$('#watch-video');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{}};}
let settings=readSettings(storage,params,reduced.matches),target=0,decoded=0,ready=false,interacted=false,seekBusy=false,seekTimer=0;
let width=0,height=0,scrollRange=1,quietTimer=0,scrollRaf=0,resizeRaf=0,controller,blobUrl='',loadGeneration=0,modalScroll=0,modalOpener,modalActive=false,keyboardInput=false,resizing=false;
const save=()=>{try{storage.setItem('mk-business-film-v1',JSON.stringify(settings));}catch{}};
const roundTime=t=>Math.min(DURATION-1/30,Math.round(clamp(t,0,DURATION)*30)/30);
function cue(t){let index=0;for(let i=1;i<chapters.length;i++)if(t>=chapters[i][0])index=i;return index;}
function updateUI(t){const index=cue(t);$('#scene-name').textContent=chapters[index][ar?2:1];$('#time').innerHTML=`${clock(t)} <span>/ 01:48</span>`;timeline.value=String(t);timeline.style.setProperty('--played',`${t/DURATION*100}%`);timeline.setAttribute('aria-valuetext',`${clock(t)} / 01:48`);$('#edge-progress').style.transform=`scaleX(${t/DURATION})`;$('#opening').hidden=t>3||settings.manual;document.querySelectorAll('[data-jump]').forEach((el,i)=>el.setAttribute('aria-current',String(index===i)));stage.dataset.time=t.toFixed(3);}
function paint(t=decoded){if(!ready||video.readyState<2||!width||!height)return;ctx.clearRect(0,0,picture.width,picture.height);const rect=pictureRect(video.videoWidth,video.videoHeight,picture.width,picture.height,settings);ctx.drawImage(video,rect.x,rect.y,rect.w,rect.h);if(settings.framing==='fit'){const back=pictureRect(video.videoWidth,video.videoHeight,ambient.width,ambient.height,defaults());bg.drawImage(video,back.x,back.y,back.w,back.h);}stage.dataset.revealed=String(interacted);stage.dataset.decodedTime=t.toFixed(3);}
// A paused, hidden video need not produce compositor frame callbacks. Native
// seek completion is the reliable signal that its pixels are ready to paint.
function finishSeek(){if(!ready||video.seeking||video.readyState<2)return;clearTimeout(seekTimer);decoded=video.currentTime;paint(decoded);seekBusy=false;stage.dataset.seekState='complete';if(Math.abs(roundTime(target)-video.currentTime)>1/60)requestAnimationFrame(pump);}
function checkSeek(){if(!ready)return;if(video.seeking||video.readyState<2){seekTimer=setTimeout(checkSeek,350);return;}finishSeek();}
function pump(){if(!ready||seekBusy||video.seeking)return;const next=roundTime(target);if(Math.abs(video.currentTime-next)<1/60){paint(video.currentTime);return;}seekBusy=true;stage.dataset.seekState='seeking';video.currentTime=next;clearTimeout(seekTimer);seekTimer=setTimeout(checkSeek,350);}
video.addEventListener('seeked',finishSeek);
function setTarget(t){target=clamp(t,0,DURATION);interacted=true;updateUI(target);pump();}
function goTo(t){setTarget(t);if(!settings.manual)window.scrollTo({top:scrollAtTime(target,scrollRange),behavior:'instant'});}
function onScroll(){if(scrollRaf||settings.manual||modalActive||resizing||width!==stage.clientWidth||height!==stage.clientHeight)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;if(modalActive||settings.manual||resizing)return;setTarget(timeAtScroll(window.scrollY,scrollRange));if(settings.controls==='auto'&&!stage.contains(document.activeElement))stage.dataset.quiet='true';});}
function keepVisible(){clearTimeout(quietTimer);stage.dataset.quiet='false';if(settings.controls==='auto'&&ready&&!settings.manual)quietTimer=setTimeout(()=>{if(!document.querySelector('dialog[open]')&&!stage.contains(document.activeElement))stage.dataset.quiet='true';},2400);}
function size(preserve=true){width=stage.clientWidth;height=stage.clientHeight;const ratio=devicePixelRatio||1;picture.width=Math.round(width*ratio);picture.height=Math.round(height*ratio);ambient.width=Math.round(width/3);ambient.height=Math.round(height/3);runway.style.height=settings.manual?'100svh':`${settings.pace*100}svh`;scrollRange=Math.max(1,runway.offsetHeight-stage.offsetHeight);if(preserve&&!settings.manual&&!document.querySelector('dialog[open]'))window.scrollTo({top:scrollAtTime(target,scrollRange),behavior:'instant'});paint();}
function syncForm(){form.querySelectorAll('input[type=radio]').forEach(el=>el.checked=String(settings[el.name])===el.value);['zoom','x','y'].forEach(key=>form.elements.namedItem(key).value=settings[key]);$('#manual').checked=settings.manual;$('#controls').value=settings.controls;$('#zoom-value').textContent=`${Math.round(settings.zoom*100)}%`;$('#x-value').textContent=`${settings.x}%`;$('#y-value').textContent=`${settings.y}%`;$('#crop-settings').hidden=settings.framing==='fit';stage.dataset.framing=settings.framing;stage.dataset.mode=settings.manual?'manual':'scroll';document.documentElement.style.setProperty('--accent',{amber:'#edb15d',teal:'#80d6ca',white:'#edf1f3'}[settings.accent]);}
function apply(next){const before=settings;settings=sanitize(next,reduced.matches);save();syncForm();if(before.pace!==settings.pace||before.manual!==settings.manual)size();paint();updateUI(target);keepVisible();}
form.addEventListener('submit',event=>event.preventDefault());form.addEventListener('input',()=>{const values=Object.fromEntries(new FormData(form));values.manual=$('#manual').checked;apply(values);});
timeline.addEventListener('input',()=>{goTo(Number(timeline.value));keepVisible();});
$('#restart').addEventListener('click',event=>{event.preventDefault();goTo(0);keepVisible();});
function openDialog(dialog,opener){modalActive=true;cancelAnimationFrame(scrollRaf);scrollRaf=0;modalScroll=window.scrollY;modalOpener=opener;document.documentElement.classList.add('modal-open');dialog.showModal();keepVisible();}
function closeDialog(dialog){dialog.close();}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('[data-close]').addEventListener('click',()=>closeDialog(dialog));dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog(dialog);}});dialog.addEventListener('close',()=>{document.documentElement.classList.remove('modal-open');if(dialog.id==='watch-dialog'){watch.pause();if(watch.readyState>=1)setTarget(watch.currentTime);}const restore=()=>{if(!settings.manual)window.scrollTo({top:scrollAtTime(target,scrollRange),behavior:'instant'});else window.scrollTo({top:Math.min(modalScroll,document.documentElement.scrollHeight-innerHeight),behavior:'instant'});};restore();if(keyboardInput)modalOpener?.focus({preventScroll:true});else document.activeElement?.blur();requestAnimationFrame(()=>{restore();requestAnimationFrame(()=>{modalActive=false;});});keepVisible();});});
$('#open-view').addEventListener('click',event=>openDialog($('#view-dialog'),event.currentTarget));
$('#open-chapters').addEventListener('click',event=>openDialog($('#chapter-dialog'),event.currentTarget));
chapters.forEach(([time,en,arabic],index)=>{const li=document.createElement('li'),button=document.createElement('button');button.type='button';button.dataset.jump=time;button.innerHTML=`<time>${clock(time)}</time><span>${ar?arabic:en}</span><span aria-hidden="true">↗</span>`;button.addEventListener('click',()=>{closeDialog($('#chapter-dialog'));goTo(time);});li.append(button);$('#chapter-list').append(li);});
$('#watch').addEventListener('click',event=>{openDialog($('#watch-dialog'),event.currentTarget);if(!watch.src){watch.src='media/film.mp4';watch.addEventListener('loadedmetadata',()=>{watch.currentTime=target;},{once:true});}else watch.currentTime=target;watch.play().catch(()=>{});});
$('#reset').addEventListener('click',()=>apply(defaults(reduced.matches)));
$('#share-view').addEventListener('click',async()=>{const url=new URL(location.href);url.search='';url.searchParams.set('lang',lang);for(const [key,value] of Object.entries(settings))url.searchParams.set(key,String(value));try{await navigator.clipboard.writeText(url.href);$('#share-status').textContent=text.copied;}catch{$('#share-status').textContent=text.copyError;$('#share-link').hidden=false;$('#share-link').value=url.href;$('#share-link').select();}});
document.addEventListener('keydown',()=>{keyboardInput=true;});document.addEventListener('pointerdown',()=>{keyboardInput=false;});
stage.addEventListener('pointermove',event=>{if(event.pointerType==='mouse')keepVisible();});stage.addEventListener('click',keepVisible);stage.addEventListener('focusin',keepVisible);stage.addEventListener('focusout',()=>setTimeout(keepVisible,0));
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',()=>{resizing=true;cancelAnimationFrame(scrollRaf);scrollRaf=0;cancelAnimationFrame(resizeRaf);resizeRaf=requestAnimationFrame(()=>{size();requestAnimationFrame(()=>{resizing=false;});});},{passive:true});
reduced.addEventListener('change',event=>{if(event.matches)apply({...settings,manual:true});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(quietTimer);watch.pause();}else paint();});
function waitFor(event,timeout=20000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>done(new Error('Media timeout')),timeout);function done(error){clearTimeout(timer);video.removeEventListener(event,onReady);video.removeEventListener('error',onError);error?reject(error):resolve();}function onReady(){done();}function onError(){done(new Error('Media decoding failed'));}video.addEventListener(event,onReady,{once:true});video.addEventListener('error',onError,{once:true});});}
function loadProgress(bytes,total,complete=false){const percent=total?Math.min(complete?100:99,Math.floor(bytes/total*100)):null;$('#load-percent').textContent=percent===null?'…':`${percent}%`;if(percent===null)$('#load-progress').removeAttribute('value');else $('#load-progress').value=percent;$('#load-bytes').textContent=`${(bytes/1e6).toFixed(1)}${total?` / ${(total/1e6).toFixed(1)}`:''} MB`;}
async function loadFilm(){const generation=++loadGeneration;controller?.abort();controller=new AbortController();ready=false;stage.dataset.ready='false';seekBusy=false;clearTimeout(seekTimer);loading.hidden=false;loading.classList.remove('error');$('#load-actions').hidden=true;$('#load-label').textContent=text.loading;loadProgress(0,0);let downloadTimeout=setTimeout(()=>controller.abort(),60000);try{const manifest=await fetch('media/manifest.json',{signal:controller.signal}).then(r=>r.ok?r.json():null).catch(()=>null);const response=await fetch('media/scroll.mp4',{signal:controller.signal});if(!response.ok)throw new Error('Film unavailable');const total=Number(response.headers.get('content-length'))||manifest?.scroll?.bytes||0;const chunks=[];let bytes=0;if(response.body){const reader=response.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);bytes+=value.length;loadProgress(bytes,total);}}else{const buffer=await response.arrayBuffer();chunks.push(buffer);bytes=buffer.byteLength;}clearTimeout(downloadTimeout);if(generation!==loadGeneration)return;loadProgress(bytes,total||bytes,true);$('#load-label').textContent=text.preparing;if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(new Blob(chunks,{type:'video/mp4'}));const loaded=waitFor('loadeddata');video.src=blobUrl;video.load();await loaded;if(generation!==loadGeneration)return;ready=true;stage.dataset.ready='true';decoded=0;loading.hidden=true;size(false);updateUI(target);if(target>0)pump();else paint(0);keepVisible();}catch(error){clearTimeout(downloadTimeout);if(generation!==loadGeneration)return;loading.classList.add('error');$('#load-label').textContent=text.failed;$('#load-actions').hidden=false;stage.dataset.ready='error';}}
$('#retry').addEventListener('click',loadFilm);
window.addEventListener('pagehide',()=>{controller?.abort();clearTimeout(quietTimer);clearTimeout(seekTimer);watch.pause();});
window.addEventListener('pageshow',event=>{if(event.persisted&&!ready)loadFilm();});
syncForm();size(false);target=settings.manual?0:timeAtScroll(window.scrollY,scrollRange);updateUI(target);loadFilm();
